FROM node:24-alpine AS builder

WORKDIR /app
# Build arguments for environment variables
ARG VITE_API_BASE_URL
ARG VITE_APP_NAME
ARG VITE_APP_SUBTITLE
ARG VITE_MOCK_AUTH_ENABLED
ARG VITE_ENVIRONMENT
ARG VITE_CORE_KONG_BASE_URL
ARG VITE_DEFAULT_ADMIN_USER
ARG VITE_BASE_PATH

ENV VITE_API_BASE_URL=${VITE_API_BASE_URL}
ENV VITE_APP_NAME=${VITE_APP_NAME}
ENV VITE_APP_SUBTITLE=${VITE_APP_SUBTITLE}
ENV VITE_MOCK_AUTH_ENABLED=${VITE_MOCK_AUTH_ENABLED}
ENV VITE_ENVIRONMENT=${VITE_ENVIRONMENT}
ENV VITE_CORE_KONG_BASE_URL=${VITE_CORE_KONG_BASE_URL}
ENV VITE_DEFAULT_ADMIN_USER=${VITE_DEFAULT_ADMIN_USER}
ENV VITE_BASE_PATH=${VITE_BASE_PATH}

COPY package*.json ./
RUN npm ci

COPY . .
RUN npm run build

FROM node:24-alpine

WORKDIR /app

COPY --from=builder /app/dist ./dist
COPY server.js ./server.js

EXPOSE 3000

CMD ["node", "server.js"]
